<?php

abstract class Drink {
    public $desc; // 描述
    public $price; // 价格

    public function getDesc()
    {
        return $this->desc;
    }
    public function setDesc($desc)
    {
        $this->desc = $desc;
    }
    public function setPrice($price)
    {
        $this->price = $price;
    }

    public function getPrice()
    {
        return $this->price;
    }

    /**
     * 计算饮品花费
     * @return mixed
     */
    abstract public function cost();
}

class Coffer extends Drink {
    public function cost()
    {
        // TODO: Implement cost() method.
        return parent::getPrice();
    }
}

class MochaCoffer extends Coffer {
    public function __construct()
    {
        $this->setDesc("摩卡咖啡");
        $this->setPrice(20);
    }
}

class LatteCoffer extends Coffer {
    public function __construct()
    {
        $this->setDesc("拿铁咖啡");
        $this->setPrice(18);
    }
}

class Decorator extends Drink {

    private $drink;

    public function __construct(Drink $drink)
    {
        $this->drink = $drink;
    }

    public function cost()
    {
        // TODO: Implement cost() method.
        return $this->drink->cost() + parent::getPrice();
    }

    public function getDesc()
    {
//        return parent::getDesc(); // TODO: Change the autogenerated stub

        return $this->desc . ':' . $this->getPrice() . " && " . $this->drink->getDesc();
    }
}

/**
 *
 * 具体的装饰者，加入的佐料
 * Class Milk
 * Class Sugar
 * Class Scream
 */

class Milk extends Decorator {
    public function __construct(Drink $drink)
    {
        parent::__construct($drink);
        $this->setDesc("牛奶");
        $this->setPrice(4);
    }
}

class Sugar extends Decorator {
    public function __construct(Drink $drink)
    {
        parent::__construct($drink);
        $this->setDesc("糖");
        $this->setPrice(2);
    }
}

class Scream extends Decorator {
    public function __construct(Drink $drink)
    {
        parent::__construct($drink);
        $this->setDesc("奶油");
        $this->setPrice(3);
    }
}

demo();

function demo() {
    // stucture_type/decorator/decorator.php
    // 装饰者下订单，拿铁咖啡，加双份糖和牛奶

    // 1.一杯拿铁
    $order = new LatteCoffer();
    print_r("拿铁咖啡，费用： {$order->cost()} <br/>");
    print_r("描述： {$order->getDesc()} <br/>");

    // 2.加一份糖
    $order = new Sugar($order);
    print_r("拿铁咖啡 + 糖 ，费用： {$order->cost()} <br/>");
    print_r("描述： {$order->getDesc()} <br/>");

    // 3.再加一份糖
    $order = new Sugar($order);
    print_r("拿铁咖啡 + 糖 * 2， 费用： {$order->cost()} <br/>");
    print_r("描述： {$order->getDesc()} <br/>");

    // 4.加一份牛奶
    $order = new Milk($order);
    print_r("拿铁咖啡 + 糖 * 2 + 牛奶，费用： {$order->cost()} <br/>");
    print_r("描述： {$order->getDesc()} <br/>");
}



