<?php

namespace app\lclsdk\Db\v1;

use think\Config;

class Db extends DbManager
{
    public $db;
    public static function __make()
    {
        $db = new static();
        $config = new Config();
        $db->setConfig($config);
    }

    public function setConfig($config): void
    {
//        parent::setConfig($config); // TODO: Change the autogenerated stub
        $this->config = $config;
    }

    public function getConfig(string $name, $default = null)
    {
//        return parent::getConfig($name, $default); // TODO: Change the autogenerated stub
        if ($name !== '') {
            // 获取 database.php 某个配置信息 如 $name = 'default' // 获取当前数据库连接; $default,当 database.$name 不存在时的默认连接配置，如mysql
            return $this->config->get('database.' . $name, $default);
        }
        // 获取 database.php 所有配置
        return $this->config->get('database', []);
    }

}