<?php

interface Brand {
    public function open();

    public function close();

    public function call();
}

abstract class Phone {
    // 组合品牌
    private $brand;

    public function __construct(Brand $brand)
    {
        $this->brand = $brand;
    }

    protected function open()
    {
        $this->brand->open();
    }

    protected function close()
    {
        $this->brand->close();
    }

    protected function call()
    {
        $this->brand->call();
    }

}

class FolderPhone extends Phone {
    public function __construct(Brand $brand)
    {
        parent::__construct($brand);
    }

    public function open()
    {
        parent::open(); // TODO: Change the autogenerated stub
        print_r("=== 折叠样式手机 ===<br/>");
    }

    public function close()
    {
        parent::close(); // TODO: Change the autogenerated stub
        print_r("=== 折叠样式手机 ===<br/>");

    }

    public function call()
    {
        parent::call(); // TODO: Change the autogenerated stub
        print_r("=== 折叠样式手机 ===<br/>");

    }
}

class UpRightPhone extends Phone {
    public function __construct(Brand $brand)
    {
        parent::__construct($brand);
    }

    public function open()
    {
        parent::open(); // TODO: Change the autogenerated stub
        print_r("=== 直立样式手机 ===<br/>");
    }

    public function close()
    {
        parent::close(); // TODO: Change the autogenerated stub
        print_r("=== 直立样式手机 ===<br/>");

    }

    public function call()
    {
        parent::call(); // TODO: Change the autogenerated stub
        print_r("=== 直立样式手机 ===<br/>");

    }
}

class XiaoMi implements Brand {
    public function open()
    {
        // TODO: Implement open() method.
        print_r("=== 小米手机开机 ===<br/>");
    }

    public function close()
    {
        // TODO: Implement close() method.
        print_r("=== 小米手机关机 ===<br/>");
    }

    public function call()
    {
        // TODO: Implement call() method.
        print_r("=== 小米手机打电话 ===<br/>");
    }
}

class Vivo implements Brand {
    public function open()
    {
        // TODO: Implement open() method.
        print_r("=== Vivo手机开机 ===<br/>");
    }

    public function close()
    {
        // TODO: Implement close() method.
        print_r("=== Vivo手机关机 ===<br/>");
    }

    public function call()
    {
        // TODO: Implement call() method.
        print_r("=== Vivo手机打电话 ===<br/>");
    }
}

demo();

function demo() {
    // stucture_type/bridge/Bridge.php
    $phone = new FolderPhone(new Vivo());
    $phone->open();
    $phone->call();
    $phone->close();
    echo '<hr/>';
    $phone1 = new FolderPhone(new XiaoMi());
    $phone1->open();
    $phone1->call();
    $phone1->close();
    echo '<hr/>';
    $phone2 = new UpRightPhone(new Vivo());
    $phone2->open();
    $phone2->call();
    $phone2->close();
}

